### ISSUE TITLE
Implementar no client metodo que una criar e verificar conta num marketplace

### ISSUE THREAD

**Issue by rscouto** [iugu/iugu-net#22]

**Comment by TiagoGouvea** [comment]
Existe previsão de implementação deste recurso?

**Comment by rscouto** [comment]
Previsão não tem tiago, 
Mas essa funcionalidade é apenas para unir 2 funcionalidades que já existem separadas no clinet, a de **Criar uma Conta** e a de enviar uma **Solicitação de Verificação** em uma unica chamada no client, mas que internamente continuaria fazendo 2 chamadas a API da IUGU. Seria só um facilitador mesmo. Entendeu?

**Comment by rscouto** [comment]
Alterei a descrição com o objetivo de tentar deixar mais claro o objetivo dessa tarefa.

Obrigado

**Comment by TiagoGouvea** [comment]
Ok. Desculpe ai, estava trabalhando com uma base de código aqui desatualizada, que não tinha o Marketplace... agora clonei a versão atual e está ok. Sem problemas, dá pra criar de boa aqui. Valeu!

**Comment by rscouto** [comment]
Nos testes integrados tem exemplos, lembrando que diferente das outras APis a **verificação de conta** só pode ser solicitada unsando o **UserToken**
