### ISSUE TITLE
Deixar mensagens de erro acessíveis

### ISSUE THREAD

**Issue by alepaez** [iugu/iugu-net#40]
https://github.com/iugu/iugu-net/blob/f3b0ec5972a10d6b48346fdbd99ac40f9e89e387/iugu.net/Lib/APIResource.cs#L166

Nessa linha estamos dando throw numa exception com o reasonPhase da request. Segundo a documentação do c#, esse campo retorna uma string descrevendo o status da request (422 -> Unprocessable Entity, 404 -> Not Found), porém a API da iugu retorna uma mensagem detalhada sobre o erro no corpo da request.

**Comment by rscouto** [comment]
O Formato de retorno ao invés de apenas a **ReasonPhase** passou a ser no, formato como do exemplo abaixo:

```json
{
    "StatusCode":404,
    "ReasonPhase":"Not Found",
    "Message": {"errors":"Customer Not Found"}
}
```
