### ISSUE TITLE
Erro ao incluir invoice: total deve ser maior que 0

### ISSUE THREAD

**Issue by TiagoGouvea** [iugu/iugu-net#43]
Ao incluir uma fatura obtive o seguinte retorno:

`{"StatusCode":422,"ReasonPhase":"Unprocessable Entity","Message":"{\"errors\":{\"total\":[\"deve ser maior que 0\"]}}"}`

Porém não existe "total" no item, eu apenas estava usando "price" ao invés de "price_cents". Talvez seja uma boa ajustar a mensagem da api.

**Comment by rscouto** [comment]
Coloca os detalhes da chamada que vc fez @TiagoGouvea  que dados vc está passando e para que API? Invoice? Vc não deve estar passando nenhum item ou o item com valor zerado.

**Obs:** Esse tipo de mudança de mensagem de retorno é algo que vc deve solicitar no Suporte da IUGU o client não muda as respostas da API da IUGU.

**Comment by rscouto** [comment]
Conseguiu resolver @TiagoGouvea ? Podemos fechar essa issue?
