### ISSUE TITLE
Inclusão do atributo PayerModel (payer{}) para a classe InvoiceRequestMessage

### ISSUE THREAD

**Issue by ayslanr** [iugu/iugu-net#44]
Prezados(as),

Sugiro a inclusão do objeto payer{} (PayerModel) para a classe InvoiceRequestMessage, pois hoje é só possível informá-lo no objeto ChargeRequestMessage.

Como preciso customizar data de vencimento e outros itens da invoice, o objeto Charge não atende.

Com a exigência de emissão de boletos registrados, preciso informar mais dados do pagador, além de apenas o e-mail do pagador.

Obrigado,
Ayslan Flores

**Comment by rscouto** [comment]
* Disponivel na versão 1.7.x do Client

Fix #44
