### ISSUE TITLE
APIResource.PostAsync => SendRequestAsync - Espera por uma resposta por tempo indeterminado

### ISSUE THREAD

**Issue by alepaez** [iugu/iugu-net#52]
Alguns clientes relataram não receber respostas dos métodos assíncronos. Vocês tem alguma ideia do que poderia estar causando esse problema?

Para nessa linha: 
https://github.com/iugu/iugu-net/blob/vnext/iugu.net/Lib/APIResource.cs#L108

Abraços

**Comment by rscouto** [comment]
@alepaez só dá pra saber com a requisição enviada e todos os detalhes da chamada, a principio todo método assincrono deve ser chamado com o await na frente no C#. 

Pode ser problema na forma de chamada mesmo do cliente, ou pode ser algum parametro específico sendo enviado.

Abraços!

**Comment by HarunoKenobi** [comment]
É muito estranho, porque não mexi no core da biblioteca, usei o método que está exatamente no projeto de teste e inclusive hoje de manhã funcionou, mas ontem e hoje na parte da tarde não funcionou mais.

Não mostra erro nem nada, simplesmente não responde. E isso acontece com qualquer método CreateAsync.

**Comment by rscouto** [comment]
@HarunoKenobi,

Você pode por favor me dar um exemplo do que está passando no parametro **CustomerRequestMessage** por exemplo. Porque eu talvez consiga reproduzir o erro e te ajudar.

**Comment by HarunoKenobi** [comment]
var customer = new iugu.net.Request.CustomerRequestMessage
            {
                Email = "arthur.g.c.souza@outlook.com.br",
                Name = "Haruno Kenobi",
                CustomVariables = customVariables
            };
            using (var apiCustomer = new Customer())
            {
                return await apiCustomer.CreateAsync(customer, "677419fc7ad6b453a0dca23885306026").ConfigureAwait(true);
            }

**Comment by rscouto** [comment]
@HarunoKenobi 

O que você envia em custom variables? Esse é seu token de produção se for apaga do comentário do Git

**Comment by HarunoKenobi** [comment]
É de token de teste apenas. Então, pensando que o problema poderia ser o CreateAsync do Customer, eu  o separei do código de teste ao qual compiei, e ficou assim:

public static async Task<CustomerModel> getCustomer()
        {
            var customVariables = new List<CustomVariables>
            {
                new CustomVariables { name = "TaxaIugu", value = "2,50" },
                new CustomVariables { name = "TaxaPlataformaEdux", value = "1,00" }
            };

            var customer = new iugu.net.Request.CustomerRequestMessage
            {
                Email = "arthur.g.c.souza@outlook.com.br",
                Name = "Haruno Kenobi",
                CustomVariables = customVariables
            };
            using (var apiCustomer = new Customer())
            {
                return await apiCustomer.CreateAsync(customer, "677419fc7ad6b453a0dca23885306026").ConfigureAwait(true);
            }
        }

O restante do método ficou da seguinte forma:

using (var apiInvoice = new Invoice())
                using (var apiCustomer = new Customer())
                using (var apiSubscription = new Subscription())
                using (var apiPlan = new Plans())
                {
                    CustomerModel customerResponse = await getCustomer();

                    var radomPlan = Guid.NewGuid().ToString();
                    var plan = await apiPlan.CreateAsync($"{radomPlan}-12x", $"{radomPlan}-Plan", 1, "months", 0, "BRL", null, null, Constants.PaymentMethod.BANK_SLIP).ConfigureAwait(false);
                    var subscriptionItems = new List<SubscriptionSubitem> { new SubscriptionSubitem { description = "Mensalidade", price_cents = 65000, quantity = 1, recurrent = true } };
                    var subscription = await apiSubscription.CreateAsync(new iugu.net.Request.SubscriptionRequestMessage(customerResponse.id)
                    {
                        PlanId = plan.identifier,
                        IsCreditBased = false,
                        CustomVariables = customVariables,
                        Subitems = subscriptionItems
                    }).ConfigureAwait(false);

                    var invoiceItems = new Item[] { new Item { description = "Mensalidade", price_cents = 65000, quantity = 1 } };
                    var invoiceRequest = new iugu.net.Request.InvoiceRequestMessage("haruno.kenobi@gmail.com.br", invoiceDate, invoiceItems)
                    {
                        //SubscriptionId = subscription.id,
                        CustomVariables = customVariables.ToArray(),
                    };

                    return invoice = await apiInvoice.CreateAsync(invoiceRequest, ConfigurationManager.AppSettings["iuguApiKey"].ToString()).ConfigureAwait(false);
                };

Que é identico aos métodos de teste.

**Comment by idanielcosta** [comment]
Consegui achar e corrigir o problema

o método SetContent é que estava com o problema realmente, mudei ele e consegui fazer funcionar.

O original era:
        private async Task SetContent(object data, HttpRequestMessage requestMessage)
        {
            if (data != null)
            {
                var content = await Task.Factory.StartNew(() => JsonConvert.SerializeObject(data, JsonSettings)).ConfigureAwait(false);
                requestMessage.Content = new StringContent(content, Encoding.UTF8, "application/json");
            }
        }

mudei para:
        private void SetContent(object data, HttpRequestMessage requestMessage)
        {
            if (data != null)
            {
                var content = JsonConvert.SerializeObject(data, JsonSettings);
                requestMessage.Content = new StringContent(content, Encoding.UTF8, "application/json");
            }
        }

e na chamada estava:

                await SetContent(data, requestMessage);

e mudei para 

                SetContent(data, requestMessage);

Testei no IIS local e no nosso servidor de produção e funcionou. Esse problema acontecia somente no IIS, já no meu projeto de testes unitários funcionava normalmente.

**Comment by rscouto** [comment]
@idanielcosta,

Poderia por gentileza fazer um teste no seu ambiente?

```csharp
private async Task SetContent(object data, HttpRequestMessage requestMessage)
{
    if (data != null)
    {
        // Trocar essa linha
        var content = await Task.Factory
                                .StartNew(() => JsonConvert.SerializeObject(data, JsonSettings))
                                .ConfigureAwait(false);
        requestMessage.Content = new StringContent(content, Encoding.UTF8, "application/json");
    }
}

private async Task SetContent(object data, HttpRequestMessage requestMessage)
{
    if (data != null)
    {
        // Por essa linha
        var content = await Task.FromResult(JsonConvert.SerializeObject(data, JsonSettings))
                                .ConfigureAwait(false);
        requestMessage.Content = new StringContent(content, Encoding.UTF8, "application/json");
    }
}
```

Você poderia dar uma ajuda fazendo esse teste, porque em meu ambiente mesmo em produção usando IIS8 não tenho problema algum, sua versão do IIS é qual? Ser servidor roda que versão do Windows?

Desde já Obrigado pela ajuda!

**Comment by idanielcosta** [comment]
Deu certo sim. Vai ficar assim?

Obrigado @alepaez

**Comment by HarunoKenobi** [comment]
Desculpe a noobisse, mas precisa de fazer algo em especial para compilar a biblioteca? O visual studio diz que o build foi bem sucedido, consigo colocar as bibliotecas no projeto web services, compila, mas quando mando rodar dá essa mensagem:
"Could not load file or assembly 'iugu.net' or one of its dependencies. An attempt was made to load a program with an incorrect format"

**Comment by rscouto** [comment]
Vou subir uma versão 1.7.2 agora @idanielcosta! Muito obrigado!

Espero que resolva para o @HarunoKenobi também, muito estranho isso ocorrer, mas enfim, coisas da vida..rsrs.

O suporte a async tem que ser Full, agora sem querer me intrometer no seu processo ai @idanielcosta, nem querer dar uma de professor (Porque não sou mesmo, e se você ja sabe isso, foi mal ai).

Mas ficar chamando a Api assincrona com um **.Result**, vc perde muito, sua aplicação vai entrar em um estado de locking até terminar a chamada, ai você perde as vantagens de poder atender outros clientes enquanto essa chamada não finaliza, pensa que web é sempre um IO lento, em comparação a memória e até mais lento que acesso a disco, na maior parte dos casos, quanto mais assincrono for seu IO de REDE melhor pra responsividade da sua aplicação.

**Comment by idanielcosta** [comment]
@rscouto, não domino essas chamadas assincronas, mas no meu caso específico eu não posso continuar enquanto não tiver a resposta, e ela é o último item do meu método. Tenho que pesquisar sobre elas, de qualquer forma obrigado pela dica.

**Comment by rscouto** [comment]
@HarunoKenobi,

Nunca testei num webservice, mas a principio os requisitos são:
* VS 2015
* Ultima versão do .Net (> 4.6)
* Instalar os pacotes via Nuget

**Comment by HarunoKenobi** [comment]
hmmm...eu fiz tudo isso, instalando o iugu.net pelo nuget funciona de boas, mas eu compilando está dando essa mensagem. :(

**Comment by rscouto** [comment]
@HarunoKenobi  deixa ver se entendi,

Você **não** instalou via nuguet vc baixou  em outro projeto compilou e fez referencia no seu web service é isso?

**Comment by idanielcosta** [comment]
@HarunoKenobi veja se as versões utilizadas de System.Net.xxx no seu projeto são as mesmas do projeto iugu.net, ou algo no seu web.config obrigando a a usar uma versão mais nova que está referenciado no projeto iugu.net.

**Comment by rscouto** [comment]
@HarunoKenobi  isso é uma das possibilidades além das dependencias indiretas como Newtonsoft.Json, que precisa estar instalado no seu projeto de webservice também.

**Comment by rscouto** [comment]
@idanielcosta,

A combinação **async (No método) | await(Na invocação)**  é justamente para te proporcionar isso, a capacidade de chamar de forma assincrona (E esperando uma resposta), de forma bem básica o que acontece por debaixo dos panos é que uma outra thread é aberta indicando que para continuar a execução daquele método deve-se obter a tal resposta primeiro, mas o lance todo é que seu programa (Site, console...) continua responsivo, se seu sistema for usado sempre por 1 agente(pessoa ou sistema), realmente não faria diferença, mas como na maioria das vezes fazemos sistemas para mais de um usuário, ai faz uma diferença enorme. 

Coloco aqui 4 artigos de 2 amigos meus, são explicações excelentes e mais abrangentes sobre o tema, recomendo muito a leitura, são artigos pequenos, mas muito bem feitos.

* [Breno Ferreira - Async no C# 5](https://brenoferreira.wordpress.com/2011/11/06/async-no-c5/)
* [Breno Ferreira - Async no C# 5–Advanced](https://brenoferreira.wordpress.com/2012/01/03/async-no-c-5advanced/)
* [Elemar JR - Parallel/Asyncronous Programming mais fácil com o Async CTP](http://elemarjr.com/pt/2012/01/03/parallel-programming-mais-fcil-com-o-async-ctp/)
* [Elemar JR - Async (advanced) – Returning Values, Cancellation, Awaiter pattern](http://elemarjr.com/pt/2012/01/03/async-advanced-returning-values-cancellation-awaiter-pattern/)

**Comment by rscouto** [comment]
@idanielcosta e @HarunoKenobi ,

Daqui a alguns minutos o nuget vai mostrar a versão 1.7.2 pra vocês. Peço que se possivel usem e informem se o problema reportado foi realmente resolvido. para que possamos fechar essa issue!

Abração a todos!

**Comment by HarunoKenobi** [comment]
Puxa, muito obrigado, não consegui rodar mesmo o projeto rsrsrrsrsrs
Vou experimentar agora depois do almoço e lhe dou um feedback.

**Comment by HarunoKenobi** [comment]
Eu testei a nova versão, infelizmente continua da mesma forma :( Ao chamar o método 'CreateAsync' o método nada mais acontece, nenhuma resposta.

**Comment by rscouto** [comment]
@HarunoKenobi,

Voce tem acesso fácil a seu servidor? Poderia instalar um programa nele? Ou se vc conseguir simular localmente maravilha, pode ser na sua maquina mesmo.

* Instala o [Fiddler4](http://www.telerik.com/fiddler) ao abrir me chama no skype(mandei pro seu endereço de email meu skype). 
Me adiciona que eu vou tentar identificar o problema contigo!

Abraço!

**Comment by HarunoKenobi** [comment]
Galera obrigado pelo suporte imediato, principalmente @rscouto, o problema era um conflito da biblioteca com o meu projeto de web service, fiz como solução o porte do meu site mvc para .net 4.6.1 e inserir o iugu nele. Houve alguns problemas de conflito das bibliotecas System.Net.Http, precisei remover tudo e add de novo por conta das dependências extras que o iugu usa. Novamente muito obrigado!!!

**Comment by diegomoschetta** [comment]
Olá,

Desculpe a pergunta, mas para que usar todos esses métodos async para fazer uma aplicação para web usando jquery por exemplo?

Pra quem não quer usar async await o jeito é reescrever a API?

**Comment by rscouto** [comment]
Não sei se entendi sua pergunta @diegomoschetta . 
Vou tentar responder mesmo assim:
* A Api é da IUGU então ela nunca terá que ser reescrita, se vc se refere ao client para API ele é feito para utilização em aplicações .Net.
* Se vc usa um SPA, ou qualquer solução sem um backend em nenhuma linguagem que rode server-side, a solução seria um client uma lib em JS. Ou como vc mesmo citou fazer as chamadas direto a API na mão.

O problema dessa abordagem é a exposição dos seu dados de acesso a API como js fica exposto, qualquer 1 poderia por exemplo ver seu live-api token e realizar, criar uma conta e realizar uma transferência, sem a sua autorização. Deu pra entender?
Eu particularmente recomento muito que todo acesso a API da IUGU seja feito server-side (mesmo em JS) pode usar node e fica tudo certo.

Enquanto ao uso do **async** e **await** o objetivo é que o server atenda multiplas requisições enquanto espera uma resposta da IUGU por exemplo. Esse padrão é altamente recomendado quando se tem muito IO seja de REDE, DISCO, BD etc.

Espero ter esclarecido sua dúvidas!

**Comment by diegomoschetta** [comment]
@rscouto, pois é acho que não soube explicar bem minha dúvida justamente por nunca ter utilizado esse formato com async e await.

Tenho uma loja virtual em c# .net desenvolvida a muitos anos e estou integrando a Api do IUGU a ela.

Confesso que não consegui montar um teste efetivo chamando essa API pela minha aplicação pois atualmente utilizo webmethods para fazer a comunicação com o server e por falta de exemplos na API com um formulário WEB utilizando ela ao invés desses testes integrados tive que recorrer ao .Result para fazer meus testes aqui.

**Comment by rscouto** [comment]
Se vc quer usar o client de forma sincrona o jeito é utilizar o .Result mesmo, problema é que se sua loja tiver muitos acessos você fica lento e limita a quantidade de request/seg atendidas sem necessidade.
