### ISSUE TITLE
Exemplo de utiização com cartão de crédito

### ISSUE THREAD

**Issue by homerokzam** [iugu/iugu-net#53]
Olá, boa noite!

Alguém possui um exemplo de como usar as seguintes funções:
1. Pré-autorizar e/ou validar um cartão de crédito
2. Realizar uma transação no cartão de crédito

Obrigado,
Homero.

**Comment by rscouto** [comment]
@homerokzam,

Homero voê já deu uma olhada na documentação da IUGU?
