### ISSUE TITLE
Como recuperar os erros?

### ISSUE THREAD

**Issue by guiggsrm** [iugu/iugu-net#54]
Estou iniciando agora a integração e vi que com a utilização da API, caso tenha algum erro, o objeto é criado de forma normal sem os dados. Veja o exemplo:
````
using (IHttpClientWrapper stubHttpClient = new StandardHttpClient())
using (IApiResources apiClient = new APIResource(stubHttpClient))
using (var client = new Account(apiClient))
{
     verifyAccountResponse = await client.VerifyUnderAccountAsync(requestAccountVerify, response.AccountId, response.UserToken).ConfigureAwait(false);
}
````

Recebi uma exception do Json com caracteres que não consegui tratar de nenhuma forma:

`{"StatusCode":422,"ReasonPhase":"Unprocessable Entity","Message":"{\"errors\":{\"cnpj\":[\"n\\u00e3o pode ficar em branco\",\"n\\u00e3o \\u00e9 v\\u00e1lido\"],\"bank_cc\":[\"d\\u00edgito invalido. (Formato: Ag\\u00eancia: 9999, Conta: XXX99999999-D [X: Opera\\u00e7\\u00e3o])\"]}}"}`

Como é feito o tratamento dos erros resultados pela API?

**Comment by rscouto** [comment]
Boa noite Guilherme @guiggsrm,

Deu um pouco de trabalho corrigir esse problema, tive que criar na realidade uma solução provisória, não por causa do formato das mensagens mas porque realmente fica ruim forçar o consumidor do client a ficar parseando toda hora essa resposta.

A solução que eu fiz deve-se em parte por conta da retrocompatibildade e por conta de outro problema que é o de a api da IUGU não unificar os formatos de resposta de erro, gerando um erro na serialzização.

Com essa correção você tem 2 opções:

* Como a mensagem agora está formatada OK(sem os caracteres doidos), você pode serializar na mão com o newtowsoft.json:
```csharp
using (IHttpClientWrapper stubHttpClient = new StandardHttpClient())
using (IApiResources apiClient = new APIResource(stubHttpClient))
using (var client = new Account(apiClient))
{
    try
    {
        verifyAccountResponse = await client.VerifyUnderAccountAsync(requestAccountVerify, response.AccountId, response.UserToken).ConfigureAwait(false);
    }
    catch(Exception ex)
    {
        // Isso vai cria um objeto com o conteudo da mensagem
        var jsonMessage = await Task.FromResult(JsonConvert.DeserializeObject(ex.Message)).ConfigureAwait(false);
    }
}
```

* Criei um facilitador pra mensagem po enquanto até ficar descente na versão 2.x do client (Ajuda é muito bem vinda). Lembrando que caso escolha a primeira opção você vai precisar contornar os diferentes formatos de erro (Essa minha factory resolve).

```csharp
using (IHttpClientWrapper stubHttpClient = new StandardHttpClient())
using (IApiResources apiClient = new APIResource(stubHttpClient))
using (var client = new Account(apiClient))
{
    try
    {
        verifyAccountResponse = await client.VerifyUnderAccountAsync(requestAccountVerify, response.AccountId, response.UserToken).ConfigureAwait(false);
    }
    catch(Exception ex)
    {
        // Isso vai cria um objeto com o conteudo da mensagem
       // Esse modelo é melhor pra vc trabalhar com os erros
      var errors = await ErrorResponseMessage.BuildAsync(ex.Message).ConfigureAwait(false);
    }
}
```

Não esqueça de passar o feedback pra fechar a issue. 😄 
Disponível na versão:  **v1.8.9**
