### ISSUE TITLE
Erro em tempo de execução

### ISSUE THREAD

**Issue by fabricioveronez** [iugu/iugu-net#56]
Eu baixei a última versão, ajustei as de dependências e executei, mas ele dá erro de dependência em  tempo de execução, tentei pegar a versão do NuGet, mas ela não reconhece as classes PaymentTokenResponseMessage e PaymentTokenRequestMessage.

**Comment by rscouto** [comment]
@fabricioveronez ,

Boa tarde fabricio poderia fornecer informações adicionais sobre seu projeto:
* Versão Windows?
* Versão .NetFramework ?
* Tipo do Projeto? (Asp.Net, WebApi, Console, ClassLibrary, WebService...etc)?
* Qualquer outra informação pode ser util? (Exemplo, quais pacotes nuget)

Desde já Muito obrigado pelo feedback

**Comment by fabricioveronez** [comment]
Boa tarde,
Versão Web, Framework 4.5, projeto ASP.NET MVC, baixei via GitHub

**Comment by rscouto** [comment]
@fabricioveronez,
 
A versão que você vê por padrão é a proxima versão que estamos trabalhando a v.2.X.X

Na versão do client atual as classes que vc mencionou não possuem a palavra **message** no final, são respectivamente:  **PaymentTokenResponse** e **PaymentTokenRequest**. 

Eu fiz testes intalando a lib do zero numa aplicação console. Realmente dei mole num binding redirect que estava direcinando para uma versão errado do Newtonsoft.Json (Corrigi isso e publiquei uma versão nova), isso estáva fazendo dar um erro em execução. A correção era apenas atualizar a versão do pacote, mas de qualquer forma deixei isso corrigido na versão lançada.

Essa falta de padronização deve-se a fases diferentes do projeto. Na v2.X.X vai ficar tudo no padrão Request e Response em conformidade. Esse branch vnext que vc baixou não é a versão de produção é uma versão ainda em teste que será lançada, não utilize esse branch pra você criar sua versão do pacote.

Mas agora com a versão do próprio nuget vai estar tudo certinho

Segue os dados no novo pacote: [v.1.8.12](https://www.nuget.org/packages/iugu.net/1.8.12)
**Espero ter te ajudado, caso esteja tudo certinho pode fecha a issue por favor?**

**Comment by fabricioveronez** [comment]
@rscouto agora ele dá o erro abaixo:
 Não foi possível carregar arquivo ou assembly 'System.Net.Http, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ou uma de suas dependências. O sistema não pode encontrar o arquivo especificado.

**Comment by rscouto** [comment]
Isso em que chamada coloca o trecho de código aqui por favor quero testar no projeto de console que eu criei aqui pra ver.

**Comment by fabricioveronez** [comment]
var expectedResponse = new PaymentTokenResponse()
            {
                Id = "84bef1e19e8d4c4ea0498085b3fc3383",
                Method = Constants.PaymentMethod.CREDIT_CARD
            };

            var paymentRequest = new PaymentTokenRequest()
            {
                AccountId = "2d8b228d-4183-44b8-ad3b-b8ab0db2aacd",
                Method = Constants.PaymentMethod.CREDIT_CARD,
                Test = true,
                PaymentData = new PaymentInfoModel
                {
                    FirstName = "Rodrigo",
                    LastName = "Couto",
                    Month = "12",
                    Year = "2018",
                    Number = "4111111111111111",
                    VerificationValue = "123"
                }
            };

            System.Runtime.CompilerServices.ConfiguredTaskAwaitable<PaymentTokenResponse> paymentTokenResponse;

            // Act
            using (var apiClient = new PaymentToken())
            {
                paymentTokenResponse = apiClient.CreateAsync(paymentRequest).ConfigureAwait(false);
            }

**Comment by rscouto** [comment]
Tu pode atualizar a versão do seu projeto pra .Net v4.6 pra fazer um teste. Desistala o nuget altera o target do projeto e instala o pacote novamente por favor pode fazer esse teste. Estou achando que tem alguma parada dentro do httpclient que está dando esse problema.

**Comment by fabricioveronez** [comment]
Aqui teve o mesmo erro no 4.6

**Comment by fabricioveronez** [comment]
4.6.1 rodou ok

**Comment by fabricioveronez** [comment]
Rodando no 4.6.1 eu recebi o erro abaixo:

{"{\"StatusCode\":422,\"ReasonPhase\":\"Unprocessable Entity\",\"Message\":{\"Errors\":{\"total\":[\"deve ser maior que 1\"]}}}"}

**Comment by rscouto** [comment]
@fabricioveronez,

Esse erro é da Api vc deixou o campo total em branco, 

Mas isso é show nenhum erro do client foi lançado. Significa que é um problema nas dependencias do .Net v4.5.

Eu descobri os erros após um **dependency hell** aqui, me pediram no passado pra fazer um downgrade pro .Net 4.5, antes só rodava no 4.6 pra cima. Só que quando fiz isso alguma das dependencias do pacote, não era compativel com o v4.5 o que estava dando os erros. Eu corrigi essas questões criei aqui nos meus testes projetos apontando pra v4.5 e 4.6 do framework. Todos rodaram com sucesso.

Com isso creio que matei a questão, você pode voltar seu projeto pro v4.5, testei aqui varias vezes e funcionou ok. Só reinstalar o pacote novo em seu projeto.

Lançei uma versão nova do client com essas alterações e atualização das dependências.
A versão [**v1.8.20**](https://www.nuget.org/packages/iugu.net/1.8.20), se puder instalar essa versão em seu projeto 4.5 qualquer problema avisa por aqui mesmo. Caso tudo funcione e espero que esteja dessa vez. Fecha a issue por favor.

Ps: lembra de remover o client autual e todas as suas depênciencias.
Grande abraço e vlw, foi graças ao seu feedback que descobri e resolvi alguns problemas.

**Comment by fabricioveronez** [comment]
Show de bola rscouto, mas buscando aqui as entidades não achei nenhum campo total, sabe que campo é ?

**Comment by rscouto** [comment]
@fabricioveronez ,

A chamada que vc está fazendo é igual a do teste? Porque eu chamei aqui com os mesmo valores do teste e foi de boa. E realmente PaymentToken nao tem total, vc deve estar chamando outra api não?

**Comment by rscouto** [comment]
@fabricioveronez ,

Esse problema ainda permanece? Posso fechar a issue?
