### ISSUE TITLE
Criar pedido de saque

### ISSUE THREAD

**Issue by guiggsrm** [iugu/iugu-net#58]
Sou eu quem faz as solicitações de transferências da aplicação inteira de forma dinâmica, seja subconta ou conta principal. Não encontrei na API algo semelhante, sendo necessário a criação de um client e objetos manuais para realização do procedimento.

https://iugu.com/referencias/api#pedido-de-saque

**Comment by rscouto** [comment]
Bom dia @guiggsrm,

Existe exatamente o que vc precisa.

Dá uma olhada no seguinte teste integrado: https://github.com/iugu/iugu-net/blob/master/iugu.net.IntegratedTests/AccountIntegratedTests.cs

Nele têm o uso do pedido de saque

**Comment by guiggsrm** [comment]
Valeu....achei que ia ser um objeto fora do Account, como é o transfer.

**Comment by rscouto** [comment]
Se vc conseguir usar e estiver tudo OK, fecha a issue para mim por gentileza

**Comment by guiggsrm** [comment]
Couto,

consegui usar mas ela possui um erro conforme descrito na [Issue 59](https://github.com/iugu/iugu-net/issues/59)
