### ISSUE TITLE
Erro no response do Withdraw

### ISSUE THREAD

**Issue by guiggsrm** [iugu/iugu-net#59]
Pessoal,

erro no response do Request Withdraw. O json de retorno do Iugu é:

```
{
"id": "530706A3862D4BB49C8AC9637B850CDE",
"status": "pending",
"created_at": "2015-11-26T10:02:23-02:00",
"updated_at": "2015-11-26T10:02:23-02:00",
"reference": null,
"amount": "R$ 10,00",
"account_name": "Conta",
"account_id": "A682CECA59D74527B984CA529D7C2ED4",
"feedback": null,
"bank_address": {
"bank": "Bradesco",
"bank_cc": "11231-2",
"bank_ag": "1234",
"account_type": "Corrente"
}
}
```

Recebo sempre a exceção falando que não conseguiu converter string em decimal, mas a transferência foi solicitada. Logo fui olhar o código de vocês e está assim:
`var retorno = await Api.PostAsync<AccountRequestWithdrawResponseMessage>(new { amount = amount }, $"{targetAccountId}/request_withdraw", customUserApiToken).ConfigureAwait(false);`

Deveria estar assim:
`var retorno = await Api.PostAsync<AccountRequestWithdrawResponseMessage>(new { amount = decimal.Parse(amount.Trim().Replace("R$", "").Replace(" ", "") }, $"{targetAccountId}/request_withdraw", customUserApiToken).ConfigureAwait(false);`

**Comment by rscouto** [comment]
@guiggsrm 

Essa alteração que você solicitou é no envio que ja é um parametro decimal e logo não precisa desse parse e desse trim.
O que provavelmente pode estar ocorrendo é um erro na serialização da resposta mas que não se corrige com essa mudança que você sugeriu. Eu fiz um teste aqui mandando serializar a resposta que vc postou na issue e está dando um erro. Diferente do que vc coloou mas está. Eu vou precisar da ajuda da IUGU pra testar poque não tenho nenhuma conta agora pra efetuar um pedido de saque. Assim que corrigir e validar essa correção já publico um nuget com a correção. Mais uma vez valeu! :)

**Comment by alepaez** [comment]
@rscouto 

Boa tarde Rodrigo.

Tudo bem?

A resposta dessa API deveria ser no formato abaixo:

{
    "id": "2B925E434B324F46827580F6BC0638AB",
    "amount": "500.0"
}

Nem teria o valor localizado ai (ex: "R$500,00"). Podemos conversar por skype para tentar identificar o que está acontecendo?

Abraços!

**Comment by guiggsrm** [comment]
Rodrigo,

verifiquei que o código do nuget está desatualizado e até meio estranho. A versão que eu utilizava era 1.8.9 e agora a versão mais atual é 1.8.2. Independentemente desta questão de versionamento, verifiquei que o objeto de response AccountRequestWithdrawResponseMessage não existe em nenhuma das versões, e sim um objeto chamado AccountRequestWithdrawResponse. Veja o código seguinte:
```
public class AccountRequestWithdrawResponse
    {
        public AccountRequestWithdrawResponse();

        [JsonProperty("account_id")]
        public string OperationId { get; set; }
        [JsonProperty("amount")]
        public decimal WithdrawValue { get; set; }
    }
```

Verifique que ele não possui Id conforme descrito pelo Alexandre e sim um account_id. Supostamente o código possa estar desatualizado no NuGet e criando erros como o descrito abaixo:

> **Could not convert string to decimal: R$ 5,00. Path 'amount', line 1, position 193.**

 conforme stack abaixo:
 ```
em Newtonsoft.Json.JsonReader.ReadDecimalString(String s)
   em Newtonsoft.Json.JsonTextReader.ReadNumberValue(ReadType readType)
   em Newtonsoft.Json.JsonTextReader.ReadAsDecimal()
   em Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   em Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   em Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   em Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   em Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   em Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   em Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   em Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   em iugu.net.Lib.APIResource.<ProcessResponse>d__25`1.MoveNext() na C:\projects\iugu-net\iugu.net\Lib\APIResource.cs:linha 166
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em iugu.net.Lib.APIResource.<PostAsync>d__19`1.MoveNext() na C:\projects\iugu-net\iugu.net\Lib\APIResource.cs:linha 129
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em iugu.net.Lib.Account.<RequestWithdrawAsync>d__8.MoveNext() na C:\projects\iugu-net\iugu.net\Lib\Account.cs:linha 99
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   em project.RN.IuguRN.<SolicitarTransferenciaFinanceira>d__18.MoveNext() na IuguRN.cs:linha 1554
```

Portanto, acredito que estamos com um erro de versionamento. Tem como nos confirmar isso?

**Comment by rscouto** [comment]
Boa tarde pessoal,

Realmente existia um problema na serialização, que corrigi na corrigi na versão lançada.

@guiggsrm esse numero que você mencionou é porque na tela do nuget não exibe um patch com mais de 1 digito, como estamos na versão 1.8.21 lançada hoje aparece 1.8.2, mas não se preocupe no nouget está certo veja a imagem abaixo:

![image](https://cloud.githubusercontent.com/assets/1678676/25049404/0db22d50-2118-11e7-82ff-c8c2756450a6.png)

Pelo que pude testar está tudo OK, hoje nao tenho uma conta real fornecida para testes pela iugu. Portanto não consegui testar apontando para dados reais.

Caso tenha mais algum problema vamos nos falando, caso tenha sido resolvido, só fechar a issue por favor.


@guiggsrm @alepaez

**Comment by alepaez** [comment]
@rscouto 
Valeu Rodrigo! Se o problema persistir eu consigo uma conta pra testar isso. 

@guiggsrm Pode confirmar se o update resolveu?

Abraços!

**Comment by guiggsrm** [comment]
@alepaez terei um saque para fazer amanhã....Te dou a resposta.

**Comment by rscouto** [comment]
@guiggsrm E ai camarada nada? Se conseguiu validar que está OK. Pode fechar a issue por favor?

**Comment by guiggsrm** [comment]
@rscouto confirmo o acerto do código.

Obrigado.
