### ISSUE TITLE
Erro no valor da constante InvoiceStatus.EXPIRED

### ISSUE THREAD

**Issue by criapix** [iugu/iugu-net#60]
O valor "Expired" da constante está com o E maiúsculo.
A API retorna com o "e" minúsculo.
Os valores das demais contantes está com tudo minúsculo.

**Comment by rscouto** [comment]
Obrigado pela ajuda Patrick (@criapix),

Corrigido na versão : **[1.8.22](https://www.nuget.org/packages/iugu.net/1.8.22)**
Qualquer problema avisa por favor. Estando OK por favor fecha a issue.

@alepaez

**Comment by criapix** [comment]
Ficou tudo OK
