### ISSUE TITLE
Atualização pendente

### ISSUE THREAD

**Issue by guiggsrm** [iugu/iugu-net#63]
Prezados,

existe atualização pendente no objeto AddressModel que é a inclusão do district. Desde hoje, 01/08, a IUGU cobra esse campo para geração do boleto.

**Comment by alepaez** [comment]
O campo district é apenas necessário para CEPs genéricos (que só referenciam a cidade), mas sim, é necessário atualizar a biblioteca para possibilitar o envio desse campo.

**Comment by HarunoKenobi** [comment]
![captura de tela de 2017-08-01 17 39 19](https://user-images.githubusercontent.com/5933675/28846156-c9c29a98-76e0-11e7-8b2f-8a9810ace6f4.png)

Estão exigindo o CEP e Numero de endereço.

**Comment by HarunoKenobi** [comment]
Eu fiz uma solução paleativa, compilei o fonte incluindo dois novos campos dentro de CustumerRequesteMessage.cs para poder criar o usuario com os dois campos obrigatórios, fiz isso porque a produção estava parada.

**Comment by rscouto** [comment]
Pessoal adicionei essas alterações a versão:
Versão com a alteração - **[v.1.9.0](https://preview.nuget.org/packages/iugu.net/1.9.0)**

Qualquer problema só falarem e Pull Requests são bem vindas! Por favor fechem as issues se estiver tudo OK.

@alepaez , @HarunoKenobi , @guiggsrm , @criapx

REF #64 #63
