### ISSUE TITLE
Error: 'payer.address.district' não pode ficar em branco

### ISSUE THREAD

**Issue by criapix** [iugu/iugu-net#64]
Temos casos de pagadores que possuem CEP com final 000. Estes CEPs são genéricos para a cidade, portanto o IUGU não consegue identificar o bairro e dá esse erro.
A propriedade 'district' deve ser incluída do AddressModel para que possa ser enviada para o IUGU.

**Comment by rscouto** [comment]
Adicionei essas alterações a versão:
Versão com a alteração - **[v.1.9.0](https://preview.nuget.org/packages/iugu.net/1.9.0)**

**Qualquer problema só falar e Pull Requests são bem vindas!**
Por favor feche a issues se estiver tudo OK.

@alepaez , @criapix

REF #64 #63

**Comment by alepaez** [comment]
Valeu @rscouto ! :D
