### ISSUE TITLE
Pergunta: Como efetuar busca por clientes usando esta api?

### ISSUE THREAD

**Issue by nvivo** [iugu/iugu-net#69]
É possível verificar a existencia de um cliente usando o email por esta api? Se sim, como?

**Comment by LimaEmanuel** [comment]
Olá, recentemente coloquei esta funcionalidade que anteriormente não existia.
Veja: [https://github.com/iugu/iugu-net/pull/75/commits/bdfa47570be6bcb26a9a6fe8c130e626484726b6](https://github.com/iugu/iugu-net/pull/75/commits/bdfa47570be6bcb26a9a6fe8c130e626484726b6)
