### ISSUE TITLE
Suporte ao .NET Standard

### ISSUE THREAD

**Issue by erickmcarvalho** [iugu/iugu-net#70]
Olá pessoal.

Eu gostaria de saber se já existe algum plano de migrarem a biblioteca para .NET Standard, tornando-a compatível tanto com .NET Framework quanto .NET Core.

Com o lançamento do .NET Standard 2.0 ficou até possível referenciar bibliotecas .NET Framework no .NET Core 2.0, mas não é totalmente compatível dependendo dos recursos utilizados do .NET Framework que ainda não foram implementados no .NET Standard 2.x, e claro, pode ser que fique limitado a ambientes Windows.

Fico no aguardo.
Abraços!

**Comment by rscouto** [comment]
Boa noite @erickmcarvalho ,

Em principio não dependemos de nenhum pacote que não esteja compativel com o .Net Core, logo com o lançamento da versãp 2.0. Você  testar e instalar no seu projeto .Net Core, caso tenha algum problema específico, reporta pra gnt que podemos investigar. Ou é claro, também pode submeter a PR!

Um Abraço,

**Comment by erickmcarvalho** [comment]
Boa tarde.

Entendi, pode ser que funcione bem.
Mas acredito que o ideal seria portar para .NET Standard, pois isso tira a limitação do Windows e muda a configuração da API, como por exemplo o uso do `ConfigurationManager` que não é utilizado no .NET Core.

Neste caso, ideal seria uma classe `Factory` totalmente independente de recursos de configurações, pois no .NET Framework tem o `ConfigurationManager` e no .NET Core o `Microsoft.Extensions.Configuration` (também utilizado no .NET Framework através do .NET Standard), entende?

Se eu tentasse portar, vocês aceitariam uma PR para uma versão futura? Uma 2.0 talvez.
Se sim, qual `branch` vocês recomendam que seja trabalhado?

Abraços!

**Comment by rscouto** [comment]
@erickmcarvalho 
Claro que aceitaria a PR essa é a idéia desse projeto, faça o fork da branch develop, depois submete o PR.

**Comment by erickmcarvalho** [comment]
@rscouto abri a PR: #77

**Comment by LimaEmanuel** [comment]
Boa tarde pessoal. Tá rolando no .NET Core já?

**Comment by erickmcarvalho** [comment]
@LimaEmanuel Pelo visto foi abandonado... mas você é livre para utilizar a minha branch.
Estou utilizando ela em projetos internos.

**Comment by LimaEmanuel** [comment]
> @LimaEmanuel Pelo visto foi abandonado... mas você é livre para utilizar a minha branch.
> Estou utilizando ela em projetos internos.

Qual é sua branch?

**Comment by erickmcarvalho** [comment]
> > @LimaEmanuel Pelo visto foi abandonado... mas você é livre para utilizar a minha branch.
> > Estou utilizando ela em projetos internos.
> 
> Qual é sua branch?

https://github.com/iugu/iugu-net/pull/77
